services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: workerexample_db
    networks:
      - workerexample_network
    environment:
      - SA_PASSWORD=1q2w3e4r!AA
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ./db:/db
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090" 
    volumes:
      - ./prometheus:/etc/prometheus 
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - back-dotnet
    networks:
      - workerexample_network
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000" 
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123 
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - workerexample_network
  loki:
    image: grafana/loki:2.7.1
    ports:
      - "3100:3100"
    #command: --config.file=/etc/loki/local-config.yaml
    #volumes:
      #- ./loki-config.yml:/etc/loki/local-config.yaml
    networks:
      - workerexample_network
  promtail:
    image: grafana/promtail:2.7.1
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - workerexample_network
  back-dotnet:
    image: wilsonsantosphx/worker-example:5
    ports:
      - 8080:8080
    networks:
      - workerexample_network
    environment:
      - ConnectionStrings__default=Server=db,1433;Database=Worker-dev;User ID=sa;Password=1q2w3e4r!AA;Trusted_Connection=False; TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=America/Sao_Paulo
    depends_on:
      - db
    restart: always
volumes:
  grafana-storage:
networks:
  workerexample_network:
    driver: bridge